### ISSUE TITLE
Unable to display vector tiles in Tangram and MapboxGL JS

### ISSUE THREAD

**Issue by bchartier** [Oslandia/postile#5]
I encounter some troubles to display the content of the pbf tiles in Tangram and MapboxGL.
I am able to download the pbf tiles.
There is no error in the logs of Postile (in debug mode).
The SQL requests sent to PostgreSQL retrieve somme records.
To verify this I've transformed the following request coming from the logs:
```
select st_simplify(geom, 19.109257071294063, true), st_makebox2d(st_point(543008.648937892, 5733388.617614501), st_point(547900.6187481433,5738280.587424751))
from mytable
where st_makebox2d(st_point(543008.648937892, 5733388.617614501), st_point(547900.6187481433,5738280.587424751)) && geom
```

into this kind of request:
```
select count(*)
from mytable
where st_makebox2d(st_point(543008.648937892, 5733388.617614501), st_point(547900.6187481433,5738280.587424751)) && geom
```

MapboxGL JS and Tangram retrieve the pbf tiles but nothing is displayed in the map. When I switch my layer to another tile server (like TileServerGL) everything is ok.

I have started Postile with that kind of command (within a docker container):
```
  postile:
    build: ./postile
    command: postile --pgport 5432 --pguser user --pgpassword password 
                     --pgdatabase database --pghost postgres
                     --listen 0.0.0.0 --listen-port 8000 --cors --debug
    ports:
      - "8010:8000"
```

I suppose I'm missing some kind of obvious parameter. Any idea?
Is there a simple way to check the data contained in the pbf tiles?
